export enum TypeOption {
  MARIAGE = 'MARIAGE',

  LOTO3CHIF = 'LOTO3CHIF',

  LOTO4CHIF = 'LOTO4CHIF',

  LOTO5CHIF = 'LOTO5CHIF',

  PREMIERLOT = 'PREMIERLOT',

  DEUXIEMELOT = 'DEUXIEMELOT',

  TROISIEMELOT = 'TROISIEMELOT',

  ALEATOIRE = 'ALEATOIRE',

  LOTO4CHIFOPTION1 = 'LOTO4CHIFOPTION1',

  LOTO4CHIFOPTION2 = 'LOTO4CHIFOPTION2',

  LOTO4CHIFOPTION3 = 'LOTO4CHIFOPTION3',

  LOTO5CHIFOPTION1 = 'LOTO5CHIFOPTION1',

  LOTO5CHIFOPTION2 = 'LOTO5CHIFOPTION2',

  LOTO5CHIFOPTION3 = 'LOTO5CHIFOPTION3',
}
